version: "3.8"

services:
  strapi:
    build: .
    container_name: strapi-app
    ports:
      - "1337:1337"
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/.tmp
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      NODE_ENV: development
