name: Deploy to Azure Container Instances

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login na Azure
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Criar Resource Group (caso n√£o exista)
        run: |
          az group create \
            --name a3-rg \
            --location eastus

      - name: Deploy no Azure Container Instances
        run: |
          az container create \
            --resource-group a3-rg \
            --name a3-strapi-container \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/strapi-a3:latest \
            --cpu 1 \
            --memory 1 \
            --ports 1337 \
            --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username $(az acr credential show --name ${{ secrets.ACR_NAME }} --query username -o tsv) \
            --registry-password $(az acr credential show --name ${{ secrets.ACR_NAME }} --query passwords[0].value -o tsv)
